apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flag
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nascied/fiap-tech-challenge-fase-3-infra
    targetRevision: HEAD
    path: fiap-tech-challenge-fase-3-infra/gitops/flag
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
