apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: default
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/auth:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
