apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation
  namespace: default
  labels:
    app: evaluation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation
  template:
    metadata:
      labels:
        app: evaluation
    spec:
      containers:
        - name: evaluation
          image: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/evaluation:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
