apiVersion: v1
kind: Service
metadata:
  name: evaluation
  namespace: default
spec:
  selector:
    app: evaluation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
